### ISSUE TITLE
Add support papirus folders ?

### ISSUE THREAD

**Issue by Boria138** [taiwbi/gnome-accent-directories#7]
The papirus-folder has all the accent colors, why not add support for this icon pack to the extension ?

**Comment by taiwbi** [comment]
You'll be able to set custom icon themes for each accent color soon (or, you know, 'soon-ish').

**Comment by taiwbi** [comment]
Now, you can choose any icon theme installed on your system for each accent color.

**Comment by fdinardo** [comment]
Hi, I see the ability to customize the look of every colors and decide which one to use among the icons installed in our system, however, I am using the `papirus-icon-theme`  from ArchLinux `[extra]` repository.
With this package we can change the folder icons color only through a script `papirus-folder` which replace the folder color without creating a new "entry" in the icons list.

@Boria138 did you figure it out ?
@taiwbi is there a feature in your roadmap to associate a bash script optionally, instead of the icon theme for a color ?
Thanks
